services:
  odoo16:
    image: odoo:16.0
    env_file: myenvfile.env
    depends_on:
      - psql
    ports:
      - "8069:8069" #port mapping(custom-port:8069)
    volumes:
      - data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./custom-addons:/mnt/extra-addons
      
  psql:
    image: postgres:13
    env_file: myenvfile.env
    volumes:
      - db:/var/lib/pgsql/data/pgdata
      
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/odoo.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/proxy_params:/etc/nginx/proxy_params:ro


  portainer:
    image: portainer/portainer-ce
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped
      
volumes:
  data:
  db:
  portainer_data:
