[options]
addons_path = /opt/odoo/odoo16/odoo/addons,/opt/odoo/odoo16/addons,/opt/odoo/addons_oca/account-budgeting,/opt/odoo/addons_oca/account-financial-reporting,/opt/odoo/addons_oca/account-financial-tools,/opt/odoo/addons_oca/account-reconcile,/opt/odoo/addons_oca/bank-payment,/opt/odoo/addons_oca/l10n-brazil,/opt/odoo/addons_oca/mis-builder,/opt/odoo/addons_oca/reporting-engine,/opt/odoo/addons_oca/contract
db_host = False
db_name = False
db_password = False
db_user = odoo16
log_level = info
logfile = /var/log/odoo/odoo16_server.log