server {

    listen 80;
    server_name ${HOST};

    location / {
        proxy_pass http://odoo:8069;
        include proxy_params;
    }

    location /longpolling/ {
        proxy_pass http://odoo:8072;
        include proxy_params;
    }

}
