server {

    listen 80;
    server_name ${HOST};

    # Serve static files directly via Nginx (performance optimization)
    location /static/ {
        proxy_cache_valid 200 1d;
        proxy_cache_min_uses 1;
        proxy_pass http://odoo:8069;
        expires 1d;
        include proxy_params;

    }

    location / {
        proxy_pass http://odoo:8069;
        include proxy_params;
    }

    # Configuração do proxy para o WebSocket
    location /websocket/ {
        proxy_pass http://odoo:8069;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;  # Necessário para WebSockets
        proxy_set_header Connection "upgrade";   # Necessário para WebSockets
        include proxy_params;
    }

    location /longpolling/ {
        proxy_pass http://odoo:8072;
        include proxy_params;
    }

    # Configuração do proxy para o WebSocket
    location /portainer/ {
        proxy_pass http://portainer:9000/;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        include proxy_params;
    }

}
